<?php

namespace common\tests\unit\jobs;

use common\fixtures\helpers\LeadFixtureHelper;
use common\modules\lead\models\Lead;
use common\modules\lead\models\LeadReport;
use console\jobs\LeadSmsSendJob;

class LeadSmsSendJobTest extends SmsSendJobTest {

	protected string $jobClass = LeadSmsSendJob::class;

	public function _fixtures(): array {
		return array_merge(
			LeadFixtureHelper::lead(),
			LeadFixtureHelper::reports(),
			LeadFixtureHelper::status(),
			LeadFixtureHelper::source(),
			LeadFixtureHelper::user(),
		);
	}

	public function testExecute(): void {
		$this->giveJob([
			'lead_id' => 1,
			'status_id' => 2,
			'owner_id' => 1,
		]);

		$id = $this->whenRun();
		$this->tester->assertNotEmpty($id);

		$this->tester->seeRecord(Lead::class, [
			'id' => 1,
			'status_id' => 2,
		]);

		$this->tester->seeRecord(LeadReport::class, [
			'old_status_id' => 1,
			'status_id' => 2,
			'owner_id' => 1,
			'details' => static::DEFAULT_MESSAGE_TEXT . ' - SMS_ID: ' . $id,
		]);
	}

	public function testExecuteWhenDontSend(): void {
		$this->giveJob([
			'lead_id' => 1,
			'status_id' => 2,
			'owner_id' => 1,
		]);
		parent::testExecuteWhenDontSend(); // TODO: Change the autogenerated stub
	}

}
