<?php

namespace common\modules\issue\widgets;

use common\helpers\Html;
use common\helpers\Url;
use common\models\issue\SummonDocLink;
use common\models\user\Worker;
use common\widgets\grid\ActionColumn;
use Yii;

class SummonDocsLinkActionColumn extends ActionColumn {

	public string $status;

	public string $returnUrl = '';

	public function init(): void {
		if (empty($this->returnUrl)) {
			$this->returnUrl = Url::current();
		}

		switch ($this->status) {
			case SummonDocLink::STATUS_TO_DO:
				$this->template = '{done} {confirm}';
				$this->buttons = [
					'done' => function (string $url, SummonDocLink $docLink): string {
						$url .= '&returnUrl=' . $this->returnUrl;
						return
							Html::a(
								Html::icon('check'),
								$url, [
								'title' => Yii::t('issue', 'To Confirm'),
								'aria-label' => Yii::t('issue', 'To Confirm'),
							]);
					},
					'confirm' => function (string $url, SummonDocLink $docLink): string {
						if ($docLink->summon->isOwner(Yii::$app->user->getId() || Yii::$app->user->can(Worker::PERMISSION_SUMMON_MANAGER))) {
							$url .= '&returnUrl=' . $this->returnUrl;
							return
								Html::a(
									Html::icon('ok'),
									$url, [
									'title' => Yii::t('issue', 'Confirmed'),
									'aria-label' => Yii::t('issue', 'Confirmed'),
								]);
						}
						return '';
					},

				];
				break;
			case SummonDocLink::STATUS_TO_CONFIRM:
				$this->template = '{confirm} {not-done}';
				$this->buttons = [
					'confirm' => function (string $url, SummonDocLink $docLink): string {
						if ($docLink->summon->isOwner(Yii::$app->user->getId())
							|| Yii::$app->user->can(Worker::PERMISSION_SUMMON_MANAGER)
						) {
							$url .= '&returnUrl=' . $this->returnUrl;
							return
								Html::a(
									Html::icon('ok'),
									$url, [
									'title' => Yii::t('issue', 'Confirm'),
									'aria - label' => Yii::t('issue', 'Confirm'),
									'data - method' => 'POST',
								]);
						}
						return '';
					},
					'not-done' => function (string $url, SummonDocLink $docLink): string {
						if ($docLink->done_user_id === Yii::$app->user->getId()
							|| Yii::$app->user->can(Worker::PERMISSION_SUMMON_MANAGER)
						) {
							$url .= '&returnUrl=' . $this->returnUrl;
							return
								Html::a(
									Html::icon('remove'),
									$url, [
									'title' => Yii::t('issue', 'To Do'),
									'aria - label' => Yii::t('issue', 'To Do'),
									'data - method' => 'POST',
								]);
						}
						return '';
					},
				];
				break;

			case SummonDocLink::STATUS_CONFIRMED:
				$this->template = '{not-confirmed}';
				$this->buttons = [
					'not-confirmed' => function (string $url, SummonDocLink $docLink): string {
						if ($docLink->confirmed_at === Yii::$app->user->getId() || Yii::$app->user->can(Worker::PERMISSION_SUMMON_MANAGER)) {
							$url .= '&returnUrl=' . $this->returnUrl;
							return
								Html::a(
									Html::icon('remove'),
									$url, [
									'title' => Yii::t('issue', 'To Confirm'),
									'aria-label' => Yii::t('issue', 'To Confirm'),
									'data-method' => 'POST',
								]);
						}
						return '';
					},
				];
				break;
		}
		parent::init();
	}

	function createUrl($action, $model, $key, $index) {
		$key = [
			'summon_id' => $model->summon_id,
			'doc_type_id' => $model->doc_type_id,
		];
		return parent::createUrl($action, $model, $key, $index); // TODO: Change the autogenerated stub
	}
}
