<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate' => 'Aktywuj',
    'Active' => 'Aktywny',
    'Application settings' => 'Ustawienia aplikacji',
    'Are you sure you want to delete this item?' => 'Czy jesteś pewny, że chcesz to usunąć?',
    'Are you sure you want to flush this cache?' => 'Вы уверены, что хотите сбросить этот кеш?',
    'Article categories' => 'Rodzaje konkursów',
    'Articles' => 'Konkursy',
    'Backend sidebar collapsed' => 'Ukryte menu admina',
    'Backend sidebar mini' => 'Małe menu admina',
    'Backend theme' => 'Motyw admina',
    'Boxed backend layout' => 'Prostokątny panel admina',
    'Cache' => 'Cache',
    'Cache entry has been successfully deleted.' => 'Cache usunięto pomyślnie',
    'Cache has been successfully flushed.' => 'Pomyślnie ogarnięto cache',
    'Category' => 'Kategoria',
    'Clear' => 'Wyczyść',
    'Content' => 'Treść',
	'Competition' => 'Konkursy',
    'Create' => 'Dodaj',
    'Create article' => 'Dodaj konkurs',
    'Create article category' => 'Dodaj kategorię',
    'Create item' => 'Dodaj element',
    'Create key storage item' => 'Dodaj klucz składowy',
    'Create page' => 'Dodaj strone',
    'Create tag' => 'Dodaj tag',
    'Create user' => 'Dodaj pracownika',
    'DB manager' => 'Zarządzanie Bazą Danych',
    'Delete' => 'Usuń',
    'Delete a value with the specified key from cache' => 'Usuń wartości o danym cache',
    'Disabled' => 'Wyłączony',
    'Email' => '',
    'Email confirm' => 'Potwierdź email',
    'Enabled' => 'Włączony',
    'Error #{id}' => 'Błąd #{id}',
    'Female' => 'Kobieta',
    'File manager' => 'Menadżer plików',
    'Fixed backend layout' => 'Fixed backend - motyw',
    'Flush' => 'Czyść',
    'Frontend maintenance mode' => 'Utrzymanie frontu',
    'Invalidate tag' => 'Kolidujący tag',
    'Key' => 'Кlucz',
    'Key storage' => 'Klucz dostępu',
    'Key storage items' => 'Elementy klucza',
    'Level' => 'Poziom',
    'Log time' => 'Czas logu',
    'Logout' => 'Wyloguj',
    'Logs' => 'Logi',
    'Main' => 'Głowne',
    'Male' => 'Mężczyzna',
    'Member since {0, date}' => 'W systemie od {0, date}',
    'Menu' => 'Меnu',
    'Message' => 'Wiadomość',
    'Not active' => 'Nie aktywny',
    'Other' => 'Reszta',
    'Pages' => 'Strony',
    'Password' => 'Hasło',
    'Prefix' => '',
    'Profile' => 'Profil',
    'Registration' => 'Rejestracja',
    'Roles' => 'Uprawnienia',
    'Save' => 'Zapisz',
    'Select cache' => 'Wybierz cache',
    'Settings was successfully saved.' => 'Ustawienia zostały zapisane.',
    'Sign in' => 'Zarejestruj',
    'Static pages' => 'Strony statyczne',
    'Status' => '',
    'System' => '',
    'Tag' => '',
    'TagDependency was invalidated.' => 'Zależność tagu jest nieuważniona.',
    'Tags' => 'Тagi',
    'Update' => 'Aktualizuj',
    'Update article category: {title}' => 'Aktualizacja kategorii: {title}',
    'Update article: {title}' => 'Aktualizacja konkursu: {title}',
    'Update item: {label}' => 'Aktualizacja elementu: {label}',
    'Update key storage item: {key}' => 'Aktualizacja klucza dostępu: {key}',
    'Update page: {title}' => 'Aktualizacja strony: {title}',
    'Update tag: {name}' => 'Aktualizacja tagu: {name}',
    'Update user: {username}' => 'Aktualizacja użytkownika: {username}',
    'User has been deleted.' => 'Użytkownik został usunięty.',
    'Username' => 'Login',
    'Users' => 'Użytkownicy',
    'View all' => 'Zobacz wszystko',
    'You can not remove your own account.' => 'Nie możesz usunąc tego konta.',
    'You have {num} log items' => 'Znaleziono {num} logów',
];
