<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate' => 'Aktywuj',
    'Active' => 'Aktywny',
    'Application settings' => 'Ustawienia aplikacji',
    'Are you sure you want to delete this item?' => 'Czy jesteś pewny, że chcesz to usunąć?',
    'Are you sure you want to flush this cache?' => 'Вы уверены, что хотите сбросить этот кеш?',
    'Article categories' => 'Категории статей',
    'Articles' => 'Artykuły',
    'Backend sidebar collapsed' => 'Скрыть боковую панель',
    'Backend sidebar mini' => 'Минимизировать боковую панель',
    'Backend theme' => 'Тема панели управления',
    'Boxed backend layout' => 'Коробочный шаблон панели управления',
    'Cache' => 'Кеш',
    'Cache entry has been successfully deleted.' => 'Запись была успешно удалена из кеша.',
    'Cache has been successfully flushed.' => 'Кеш был успешно сброшен.',
    'Category' => 'Категории',
    'Clear' => 'Очистить',
    'Content' => 'Контент',
    'Create' => 'Создать',
    'Create article' => 'Создать статью',
    'Create article category' => 'Создать категорию статей',
    'Create item' => 'Создать пункт',
    'Create key storage item' => 'Создать ключ',
    'Create page' => 'Создать страницу',
    'Create tag' => 'Создать тег',
    'Create user' => 'Создать пользователя',
    'DB manager' => 'БД менеджер',
    'Delete' => 'Удалить',
    'Delete a value with the specified key from cache' => 'Удалить значение по ключу из кеша',
    'Disabled' => 'Выключено',
    'Email' => '',
    'Email confirm' => 'Email подтверждение',
    'Enabled' => 'Включено',
    'Error #{id}' => 'Ошибка #{id}',
    'Female' => 'Женский',
    'File manager' => 'Файловый менеджер',
    'Fixed backend layout' => 'Фиксированный шаблон панели управления',
    'Flush' => 'Сбросить',
    'Frontend maintenance mode' => 'Сервисный режим фронтенд части',
    'Invalidate tag' => 'Сбросить тег',
    'Key' => 'Ключ',
    'Key storage' => 'Хранилище ключей',
    'Key storage items' => 'Записи',
    'Level' => 'Уровень',
    'Log time' => 'Время события',
    'Logout' => 'Выход',
    'Logs' => 'Журнал',
    'Main' => 'Главный',
    'Male' => 'Мужской',
    'Member since {0, date}' => 'Участник с {0, date}',
    'Menu' => 'Меню',
    'Message' => 'Сообщение',
    'Not active' => 'Не активно',
    'Other' => 'Прочее',
    'Pages' => 'Страницы',
    'Password' => 'Пароль',
    'Prefix' => 'Префикс',
    'Profile' => 'Профиль',
    'Registration' => 'Регистрация',
    'Roles' => 'Роли',
    'Save' => 'Zapisz',
    'Select cache' => 'Выберите кеш',
    'Settings was successfully saved.' => 'Настройки были успешно сохранены.',
    'Sign in' => 'Вход',
    'Static pages' => 'Статические страницы',
    'Status' => 'Статус',
    'System' => 'Система',
    'Tag' => 'Тег',
    'TagDependency was invalidated.' => 'TagDependency был инвалидирован.',
    'Tags' => 'Теги',
    'Update' => 'Редактировать',
    'Update article category: {title}' => 'Редактировать категорию статей: {title}',
    'Update article: {title}' => 'Редактировать статью: {title}',
    'Update item: {label}' => 'Обновить пункт: {label}',
    'Update key storage item: {key}' => 'Редактировать ключ-значение: {key}',
    'Update page: {title}' => 'Редактировать страницу: {title}',
    'Update tag: {name}' => 'Редактировать тег: {name}',
    'Update user: {username}' => 'Редактировать пользователя: {username}',
    'User has been deleted.' => 'Пользователь был удален.',
    'Username' => 'Имя пользователя',
    'Users' => 'Użytkownicy',
    'View all' => 'Zobacz wszystko',
    'You can not remove your own account.' => 'Вы не можете удалить свою учетную запись.',
    'You have {num} log items' => 'У вас {num} записей в журнале',
];
