<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktywny',
    'Author' => 'Autor',
    'Avatar' => 'Awatar',
    'Banned' => 'Zbanowany',
	'Category' => 'Rodzaj',
    'Comment' => 'Komentarz',
    'Created at' => 'W firmie od',
    'Deleted' => 'Usuń',
    'Description' => 'Opis',
    'Email' => '',
    'Firstname' => 'Imie',
    'Frequency' => 'Частота',
    'Gender' => 'Płeć',
    'Inactive' => 'Nieaktywny',
    'Key' => 'Кlucz',
    'Keywords' => 'Słowo kluczowe',
    'Last action at' => 'Ostatnia aktywność',
    'Lastname' => 'Nazwisko',
    'Link' => '',
    'Name' => 'Nazwa',
    'Other' => 'Inne',
    'Parent' => 'Rodzic',
    'Password' => 'Hasło',
    'Preview' => 'Podgląd',
    'Published at' => 'Publikowany',
    'Remember me' => 'Zapamiętaj',
    'Slug' => '',
    'Sort index' => '',
    'Status' => 'Status',
    'Tags' => 'Tagi',
    'Text' => 'Tekst',
    'Title' => 'Tytuł',
    'Updated at' => 'Aktualizacja',
    'Updater' => 'Edytor',
    'Username' => 'Login',
    'Username or email' => 'Login lub email',
    'Value' => 'uzupełnienia',
    'Website' => 'Strona',
];
