<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Active' => 'Aktywny',
	'administrator' => 'Admin',
	'agent' => 'Przedstawiciel',
	'archive' => 'Archiwum',
	'customer_service' => 'Obsługa klienta',
	'issue' => 'Sprawy',
	'lawyer' => 'Prawnik',
	'logs' => 'Logi',
	'news' => 'Newsy',
	'note' => 'Notatki',
	'Author' => 'Autor',
	'Avatar' => 'Awatar',
	'Banned' => 'Zbanowany',
	'Category' => 'Rodzaj',
	'Comment' => 'Komentarz',
	'confirm delete this' => 'Czy napewno chcesz to usunąć?',
	'Created at' => 'W firmie od',
	'Deleted' => 'Usuń',
	'Description' => 'Opis',
	'Email' => '',
	'Firstname' => 'Imie',
	'Frequency' => 'Частота',
	'Gender' => 'Płeć',
	'Inactive' => 'Nieaktywny',
	'Key' => 'Кlucz',
	'Keywords' => 'Słowo kluczowe',
	'Last action at' => 'Ostatnia aktywność',
	'layer' => 'Prawnik',
	'Lastname' => 'Nazwisko',
	'Link' => '',
	'manager' => 'Manager',
	'Name' => 'Nazwa',
	'Other' => 'Inne',
	'Parent' => 'Rodzic',
	'Password' => 'Hasło',
	'Preview' => 'Podgląd',
	'Published at' => 'Publikowany',
	'Remember me' => 'Zapamiętaj',
	'Slug' => '',
	'Sort index' => '',
	'Status' => 'Status',
	'Tags' => 'Tagi',
	'Text' => 'Tekst',
	'telemarketer' => 'Telemarketer',
	'Title' => 'Tytuł',
	'Updated at' => 'Aktualizacja',
	'Updater' => 'Edytor',
	'Username' => 'Login',
	'user' => 'Użytkownik',
	'Username or email' => 'Login lub email',
	'Value' => 'uzupełnienia',
	'Website' => 'Strona',
	'associate_director' => 'Zastępca dyrektora',
	'director' => 'Dyrektor',
	'general_director' => 'Dyrektor generalny',
	'book_keeper' => 'Księgowy',
	'book_keeper_delayed' => 'Księgowy - przeterminowane',
	'meet' => 'Spotkania',
	'victim' => 'Ofiara',
	'client' => 'Klient'
];
