<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Activation for {name}' => 'Активация для {name}',
	'Articles' => 'Newsy',
	'Articles category &laquo;{title}&raquo;' => 'News &laquo;{title}&raquo;',
	'Are you sure you want to delete this item?' => 'Czy napewno chcesz to usunąć?',
	'Backend' => 'Panel admina',

	'Change password' => 'Zmień hasło',
	'Check your email for further instructions.' => 'Sprawdź swój email',
	'Confirm password' => 'Potwierdź hasło',
	'Contact' => 'Kontakt',
	'Causes' => 'Sprawy',
	'Cause Categories' => 'Etapy',
	'Calendar' => 'Kalendarz',
	'Create Cause Category' => 'Dodaj nowy etap',
	'Create Cause' => 'Dodaj sprawę',
	'Delete' => 'Usuń',
	'Email' => '',
	'Error activate your account.' => 'Błąd przy aktywacji konta.',
	'Firstname' => 'Имя',
	'Gender' => 'Płeć',
	'Hello {username}, follow the link below to confirm your email:' => 'Привет {username}, перейдите по ссылке ниже, чтобы подтвердить ваш email:',
	'Hello {username}, follow the link below to reset your password:' => 'Привет {username}, перейдите по ссылке ниже, чтобы сбросить ваш пароль:',
	'Lastname' => 'Nazwisko',
	'Login' => 'Zaloguj',
	'Logout' => 'Wyloguj',
	'Lost password' => 'Zapomniałeś hasła?',
	'Name' => 'Imie',
	'New password was saved.' => 'Nowe hasło zostało zapisane.',
	'Other' => 'Inny',
	'Page not found.' => 'Strony nie znaleziono.',
	'Password' => 'Hasło',
	'Password reset for {name}' => 'Сброс пароля для {name}',
	'Password reset token cannot be blank.' => 'Маркер восстановление пароля не может быть пустым.',
	'Registration is disabled.' => 'Rejestracja jest wyłączona.',
	'Request password reset' => 'Przywrócenie hasła',
	'Reset password' => 'Reset hasła',
	'Save' => 'Zapisz',
	'Send' => 'Wyślij',
	'Send email' => 'Wyślij email',
	'Settings' => 'Ustawienia',
	'Signup' => 'Rejestracja',
	'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем сбросить пароль для этого email.',
	'Subject' => 'Temat',
	'Text' => 'Tekst',
	'Task' => 'Spotkania',
	'Thank you for contacting us. We will respond to you as soon as possible.' => 'Dziękujemy za kontakt',
	'There was an error sending email.' => 'Błąd przy wysyłaniu wiadomości email.',
	'Update' => 'Edytuj',
	'Username' => 'Login',
	'Users' => 'Ranking',
	'Verification code' => 'Kod weryfikacyjny',
	'Website' => 'Strona',
	'Wrong password reset token.' => 'Неверный маркер сброса пароля.',
	'Your account has been successfully activated.' => 'Twoje konto zostało aktywowane.',
	'Your tasks' => 'Twoje spotkania',
	'Your calendar' => 'Osobisty kalendarz',
	'Your account has been successfully created. Check your email for further instructions.' => 'Pomyślnie utworzono konto. Sprawdź maila po dalsze instrukcje.',
	'Your message has been sent successfully.' => 'Twoja wiadość pomyślnie została wysłana.',
	'Your password has been successfully changed.' => 'Twoje hasło zostało pomyślnie zmienione.',
	'description' => '<ul><li>afsfsa</li></ul><p><br></p><table><tbody><tr><td>213</td><td>123</td><td>123</td></tr><tr><td>123</td><td>123</td><td>123</td></tr></tbody></table>',
];
