<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Treść',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Status',
    'Level' => 'Level',
    'Created by' => 'Utworzył',
    'Updated by' => 'Edytował',
    'Related to' => 'Edytował',
    'Url' => 'Url',
    'Created date' => 'Utworzono',
    'Updated date' => 'Edytowano',
    'View' => 'Widok',
    'Update' => 'Edytuj',
    'Delete' => 'Usuń',
    'Reply' => 'Adnotacja',
    'Comments ({0})' => 'Notatki ({0})',
    'Comment cannot be blank.' => 'Notatka nie może być pusta',
    'Comment has not been deleted. Please try again!' => 'Notatka nie została usunięta, spróbuj raz jeszcze',
    'Add a comment...' => 'Podaj treść',
    'Comment' => 'Dodaj notatkę',
    'Oops, something went wrong. Please try again later.' => 'Oops, something went wrong. Please try again later.',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Comment has been deleted.' => 'Notatka została usunięta',
    'Comment has been saved.' => 'Notatka została zapisna',
    'Click here to cancel reply.' => 'Opuść adnotacje',
    'Comments Management' => 'Zarządzaj notatkami',
    'Select Status' => 'Wybierz Status',
    'Select Author' => 'Wybierz Author',
    'Update Comment: {0}' => 'Edytuj notatkę: {0}',
    'Active' => 'Aktywna',
    'Deleted' => 'Usunięta',
    'Go Back' => 'Cofnij',
];
