version: "3.2"
services:
  frontend:
    container_name: "vestratele_frontend"
    restart: "always"
    build:
      context: ""
      dockerfile: docker/development/Dockerfile-frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./:/var/html/vestra
    working_dir: /var/html/vestra
    networks:
      main:
        aliases:
          - frontend
  backend:
    container_name: "vestratele_backend"
    restart: "always"
    build:
      context: ""
      dockerfile: docker/development/Dockerfile-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./:/var/html/vestra
    working_dir: /var/html/vestra
    networks:
      main:
        aliases:
          - backend
  db_mysql:
    container_name: "vestratele_db_mysql"
    image: mysql:8.0.16
    restart: always
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DBNAME: "${DB_DBNAME}"
    volumes:
      - ./docker/development/sql/:/docker-entrypoint-initdb.d/
    ports:
      - "${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
    networks:
      main:
        aliases:
          - db_mysql

  reverse_proxy:
    image: nginx:1.9
    container_name: "vestratele_reverse_proxy"
    volumes:
      - ./docker/development/ngnx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/development/ngnx/backend-not-found.html:/var/www/html/backend-not-found.html:ro
      - ./docker/development/ngnx/includes/:/etc/nginx/includes/
      - ./docker/development/ngnx/ssl/:/etc/ssl/certs/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      main:
        aliases:
          - db_mysql

networks:
  main: