version: "3"
services:
  frontend:
    container_name: "vestratele_Frontend"
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./:/var/html/vestra
    working_dir: /var/html/vestra
    networks:
      main:
        aliases:
          - frontend
networks:
  main: