<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;
/* @var $this yii\web\View */
/* @var $searchModel common\models\TaskStatusSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Wszystkie spotkania';
$this->params['breadcrumbs'][] = $this->title;

use yii\data\SqlDataProvider;
use yii\data\ActiveDataProvider;
use  kartik\grid\GridView;
use common\models\TaskStatus;
use common\models\AnswerTyp;
use common\models\User;
use common\models\AccidentTyp;
use common\models\Wojewodztwa;



//po przedstawicielach

/* @var $this yii\web\View */
/* @var $searchModel common\models\TaskStatusSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$isFa = false;
$exportConfig=   [
	GridView::PDF => [
        'label' => Yii::t('kvgrid', 'PDF'),
        'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
        'iconOptions' => ['class' => 'text-danger'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
        'mime' => 'application/pdf',
        'config' => [
            'mode' => 'c',
            'format' => 'A4-L',
            'destination' => 'D',
            'marginTop' => 20,
            'marginBottom' => 20,
            'cssInline' => '.kv-wrap{padding:20px;}' .
                '.kv-align-center{text-align:center;}' .
                '.kv-align-left{text-align:left;}' .
                '.kv-align-right{text-align:right;}' .
                '.kv-align-top{vertical-align:top!important;}' .
                '.kv-align-bottom{vertical-align:bottom!important;}' .
                '.kv-align-middle{vertical-align:middle!important;}' .
                '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
            'methods' => [
                'SetHeader' => [
                    ['odd' => 'pdfHeader', 'even' => 'evenHader']
                ],
                'SetFooter' => [
                    ['odd' => 'pdfFooter', 'even' => 'evenFooter']
                ],
            ],
            'options' => [
                'title' => 'title heh',
                'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
            ],
            'contentBefore'=>'',
            'contentAfter'=>''
        ],
		'encoding' => 'utf8',
    ],
	GridView::EXCEL => [
        'label' => Yii::t('kvgrid', 'Excel'),
        'icon' =>'file-excel-o',
        'iconOptions' => ['class' => 'text-success'],
        'showHeader' => true,
        'showPageSummary' => true,
        'showFooter' => true,
        'showCaption' => true,
        'filename' => Yii::t('kvgrid', 'grid-export'),
        'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
        'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
        'mime' => 'application/vnd.ms-excel',
        'config' => [
            'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
            'cssFile' => ''
        ]
    ],

];

?>

<?=Html::button('Filtry', [ 'class' => 'btn btn-primary mg-15', 'onclick' => "$('#filter').toggle('drop');" ]) ?>
<div id="filter">
    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>
</div>
<div class="task-status-index">

<?php
	echo GridView::widget([
		'id' => 'kv-grid-demo',
		'dataProvider'=>$dataProvider,
		'columns'=>[
			[

			   'class' => 'yii\grid\ActionColumn',
			    'template' => '{see}',
				'buttons' => [
					  'see' => function ($url, $model, $key) {
							$options = [
								'title' => 'Podgląd',
								'aria-label' => 'Podgląd',
								'data-pjax' => '0',
							];
							$url = \yii\helpers\Url::toRoute(['task-status/raport', 'id' => $key]);

							return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, $options);
						}
				],
			],
			[	 'class' => '\kartik\grid\DataColumn',
				 'attribute' => 'id',
				 'width' => '15px',
			],
			[	 'class' => '\kartik\grid\DataColumn',
				 'attribute' => 'tele',
				 'value' => 'tele.username',
				 'label' => 'Konsultant',
				 'filter' => ArrayHelper::map(User::find()->where(['typ_work' => 'T'])->all(), 'id', 'username')
			],
			[	 'class' => '\kartik\grid\DataColumn',
				 'attribute' => 'agent',
				 'value' => 'agent.username',
				 'label' => 'Przedstawiciel',
				 'filter' => ArrayHelper::map(User::find()->where(['typ_work' => 'P'])->all(), 'id', 'username')
			],
			[
				'class' => '\kartik\grid\DataColumn',
				'attribute' => 'date',
                'format' => 'date',
			],

			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'victim_name',
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'accident',
				'value' => 'accident.name',
				'label' => 'Zdarzenie',
				'filter' => ArrayHelper::map(AccidentTyp::find()->all(), 'id', 'name')
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'wojewodztwo',
				'value' => 'wojewodztwo.name',
				'filter' => ArrayHelper::map(Wojewodztwa::find()->all(), 'id', 'name')
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'powiatRel',
				'value' => 'powiatRel.name',
				'label' => 'Powiat'
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'gminaRel',
				'value' => 'gminaRel.name',
				'label' => 'Gmina'
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'miasto',
				'value' => 'miasto.name',
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'answer',
				'value' => 'taskstatus.answer.name',
				'label' => 'Efekt',
				'filter' => ArrayHelper::map(AnswerTyp::find()->all(),'id', 'name')
			],
			[
				'class' =>
				'\kartik\grid\DataColumn',
				'attribute' => 'taskstatus.count_agreement',
			],
		],


		'filterModel'=>$searchModel,
		//'columns'=>$gridColumns,
		'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
		'headerRowOptions'=>['class'=>'kartik-sheet-style'],
		'filterRowOptions'=>['class'=>'kartik-sheet-style'],
		'pjax'=>true, // pjax is set to always true for this demo
		// set your toolbar
		'toolbar'=> [
			['content'=>
				Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=>Yii::t('kvgrid', 'Reset Grid')])
			],
			'{export}',
			'{toggleData}',

			],
		// set export properties
		'export'=>[
			'fontAwesome'=>true
			],
		'bordered'=>true,
		'striped'=>true,
		'condensed'=>true,
		'responsive'=>true,
		'hover'=>true,


		'panel'=>[
			'type'=>GridView::TYPE_PRIMARY,
			'heading'=>'<i class="glyphicon glyphicon-book"></i>  Umówione spotkania',
		],
		'persistResize'=>false,
		'exportConfig'=>$exportConfig,
	]);
?>

</div>
